container:
  dockerfile: Dockerfile-test
  cpu: 2
  memory: 8
  # image: node:latest

lint_task:      
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  test_script: npm run lint

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: MONGOMS_DOWNLOAD_MIRROR="http://downloads.mongodb.org" MONGOMS_VERSION="4.0.5" MONGOMS_DISABLE_POSTINSTALL=1 npm ci
  test_script: npm test -- --tap --verbose --serial `find . -name '*.spec.js'`

# test_docker_builder: 
#   only_if: $CIRRUS_TAG != ''
#   depends_on: 
#     - test
#     - lint
#   build_script: docker build --tag vly-test:latest -f Dockerfile-test
